name: Sync Projects from Repositories

on:
  # Run daily to check for new repositories
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  
  # Allow manual trigger
  workflow_dispatch:
  
  # Trigger when repository_dispatch event is received
  repository_dispatch:
    types: [new_repo_created]

permissions:
  contents: write

jobs:
  sync-projects:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout portfolio repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: |
          cd .github/scripts
          npm install
      
      - name: Sync repositories
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          node .github/scripts/sync-projects.js
      
      - name: Commit and push if changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add _projects/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: auto-sync projects from repositories"
            git push
          fi
